project_id = "embzslnxlpyzlimlhpaj"

[functions.submit-lead-to-ghl]
verify_jwt = false

[functions.send-circulo-otp]
verify_jwt = false

[functions.verify-circulo-otp]
verify_jwt = false

[functions.generate-analytics-insights]
verify_jwt = false

[functions.submit-brecha-lead]
verify_jwt = false

[functions.sync-brecha-tags]
verify_jwt = false

[functions.sync-brecha-tags-bulk]
verify_jwt = false

[functions.sync-senda-tags]
verify_jwt = false

[functions.sync-senda-tags-bulk]
verify_jwt = false

[functions.create-onboarding]
verify_jwt = false

[functions.claim-payment]
verify_jwt = false

[functions.get-my-invoice]
verify_jwt = true

[functions.get-my-project]
verify_jwt = true

[functions.sync-consulting-tags]
verify_jwt = false
