project_id = "yewfryggiinoebnobbuq"

[functions.submit-lead-to-ghl]
verify_jwt = false

[functions.generate-analytics-insights]
verify_jwt = false

[functions.submit-brecha-lead]
verify_jwt = false

[functions.sync-brecha-tags]
verify_jwt = false

[functions.sync-brecha-tags-bulk]
verify_jwt = false
